function lspec = getCueLineSpec(group)
% -------------------------------------------------------------------------
% usage: returns rgb values for colors used in cue experiment
%
% INPUT:
%   group - string specifying a group relevant to the cue experiment

%
% OUTPUT:
%   lspec - lspec string for plotting
%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if notDefined('group')
    group='controls';
end


%% make cell array with line specs


switch lower(group)
    
    case {'controls','control',0}
        
        lspec = '-';
        
    case {'patients',1}
        
        lspec = '--';
        
    case {'relapsers_3months','relapsers 3months',...
            'relapsers_4months','relapsers 4months',...
            'relapsers_6months','relapsers 6months',...
            'relapsers_8months','relapsers 8months',...
            'relapsers',...
            'relapsers_3months_sample1','relapsers 3months sample1',...
            'relapsers_4months_sample1','relapsers 4months sample1',...
            'relapsers_6months_sample1','relapsers 6months sample1',...
            'relapsers_8months_sample1','relapsers 8months sample1',...
            'relapsers_sample1','relapsers sample1',...
            'relapsers_3months_sample2','relapsers 3months sample2',...
            'relapsers_4months_sample2','relapsers 4months sample2',...
            'relapsers_6months_sample2','relapsers 6months sample2',...
            'relapsers_8months_sample2','relapsers 8months sample2',...
            'relapsers_sample2','relapsers sample2',...
            'relapsers_3months_for','relapsers 3months for',...
            'relapsers_4months_for','relapsers 4months for',...
            'relapsers_6months_for','relapsers 6months for',...
            'relapsers_8months_for','relapsers 8months for',...
            'relapsers_for','relapsers for',...
            'relapsers_3months_epiphany','relapsers 3months epiphany',...
            'relapsers_4months_epiphany','relapsers 4months epiphany',...
            'relapsers_6months_epiphany','relapsers 6months epiphany',...
            'relapsers_8months_epiphany','relapsers 8months epiphany',...
            'relapsers_epiphany','relapsers epiphany',...
            }
        
        lspec = '--o';
        
    case {'nonrelapsers_3months','nonrelapsers 3months',...
            'nonrelapsers_4months','nonrelapsers 4months',...
            'nonrelapsers_6months','nonrelapsers 6months',...
            'nonrelapsers_8months','nonrelapsers 8months',...
            'nonrelapsers',...
            'nonrelapsers_3months_sample1','nonrelapsers 3months sample1',...
            'nonrelapsers_4months_sample1','nonrelapsers 4months sample1',...
            'nonrelapsers_6months_sample1','nonrelapsers 6months sample1',...
            'nonrelapsers_8months_sample1','nonrelapsers 8months sample1',...
            'nonrelapsers_sample1','nonrelapsers sample1',...
            'nonrelapsers_3months_sample2','nonrelapsers 3months sample2',...
            'nonrelapsers_4months_sample2','nonrelapsers 4months sample2',...
            'nonrelapsers_6months_sample2','nonrelapsers 6months sample2',...
            'nonrelapsers_8months_sample2','nonrelapsers 8months sample2',...
            'nonrelapsers_sample2','nonrelapsers sample2',...
            'nonrelapsers_3months_for','nonrelapsers 3months for',...
            'nonrelapsers_4months_for','nonrelapsers 4months for',...
            'nonrelapsers_6months_for','nonrelapsers 6months for',...
            'nonrelapsers_8months_for','nonrelapsers 8months for',...
            'nonrelapsers_for','nonrelapsers for',...
            'nonrelapsers_3months_epiphany','nonrelapsers 3months epiphany',...
            'nonrelapsers_4months_epiphany','nonrelapsers 4months epiphany',...
            'nonrelapsers_6months_epiphany','nonrelapsers 6months epiphany',...
            'nonrelapsers_8months_epiphany','nonrelapsers 8months epiphany',...
            'nonrelapsers_epiphany','nonrelapsers epiphany',...
            }
        
        lspec = '-.*';
        
    otherwise
        
        lspec = '-';
        
end


