---
title: "pairs plots"
author: "Kelly MacNiven"
date: "3/11/2019"
output: html_document
---


get libraries & load data
```{r setup, collapse=TRUE, warning=FALSE}
require(psych)

#load data
d1 = read.csv('/Users/kelly/cueexp/data/q_demo_data/data_controls_191104.csv')
#d1 = read.csv('/Users/kelly/cueexp/data/q_demo_data/data__191022.csv')
d1$FA<-d1$inf_NAcc_fa_controllingagemotion
d1$inverseMD<-1-d1$inf_NAcc_md_controllingagemotion
d1$smoke[d1$smoke>0]=1

# just controls 
d1<-d1[d1$gi==0]

```

#pairs plots 1: age, motion, and sex

```{r pairs plot1, collapse=TRUE, warning=FALSE}

dp = with(d1, data.frame(FA,inverseMD,BIS,age,dwimotion,gender))
          
pairs.panels(dp)

```

#pairs plots 2: TIPI

```{r pairs plot2, collapse=TRUE, warning=FALSE}

dp = with(d1, data.frame(FA,inverseMD,BIS,tipi_extra,tipi_agree,tipi_consci,tipi_emostab,tipi_open))

pairs.panels(dp)

```       

#pairs plots 3: discount BIS/BAS, and BDI

```{r pairs plot3, collapse=TRUE, warning=FALSE}

dp = with(d1, data.frame(FA,inverseMD,BIS,discount_rate,basdrive,basfunseek,basrewardresp,bisbas_bis,BDI))

pairs.panels(dp)

```       

#pairs plots 4: BIS subscales

```{r pairs plot4, collapse=TRUE, warning=FALSE}

dp = with(d1, data.frame(FA,inverseMD,BIS,BIS_attn,BIS_motor,BIS_nonplan))

pairs.panels(dp)

```       

#pairs plots 5: MID fMRI measures

```{r pairs plot5, collapse=TRUE, warning=FALSE}

#dp = with(d1, data.frame(FA,inverseMD,BIS,d1$nacc_gain5_TR3,d1$nacc_gain5_TR4,d1$nacc_gvnant_beta))

#pairs.panels(dp)

```       


#pairs plots 6: supp fig for manuscript: BIS/BAS, kirby, BDI

```{r pairs plot6, collapse=TRUE, warning=FALSE}

dp = with(d1, data.frame(FA,inverseMD,discount_rate,basdrive,basfunseek,basrewardresp,bisbas_bis,BDI))

pairs.panels(dp)

```       

#pairs plots 7: supp fig for manuscript: TIPI

```{r pairs plot7, collapse=TRUE, warning=FALSE}

dp = with(d1, data.frame(FA,inverseMD,tipi_extra,tipi_agree,tipi_consci,tipi_emostab,tipi_open))

pairs.panels(dp)

```       

#pairs plots 8: supp fig: years of use, age of first use, 

```{r pairs plot8, collapse=TRUE, warning=FALSE}

dp = with(d1, data.frame(FA,years_of_use,first_use_age,smoke))

pairs.panels(dp)

```       